### ISSUE TITLE
smartthings?

### ISSUE THREAD

**Issue by fun4stuff** [maddox/dasher#90]
How does this work with smartthings? are there any config.json examples?

**Comment by maddox** [comment]
If SmartThings can accept HTTP requests to trigger things, then you'd have to check with their documentation on how to form the URLs and what HTTP methods to use to make the requests.

**Comment by elmedico27** [comment]
Try the IFTTT Webhooks (previously Maker) channel.  You can send it a POST request and then have it trigger a SmartThings action.

Steps:

1. Sign up for an IFTTT account if you haven't yet.
2. Create an applet using the Webhooks channel as your "if this" trigger, and SmartThings as the "then that" action.  Remember the event name you give your webhook; you'll need to put it in the URL in your config.json.
3. Go to the [Webhooks channel](https://ifttt.com/maker_webhooks), and click the button in the upper right that says "Documentation"; this will give you the URL to put in your config.json with your secret key. 
4. Add the following in your config.json, customizing as necessary:
```
{
    "name": "Trigger IFTTT Event",
    "address": "[dash_button_MAC]",
    "url": "https://maker.ifttt.com/trigger/[event_name]/with/key/[insert_your_key]",
    "protocol": "udp",
    "method": "POST",
    "json": true,
    "body": { "value1" : "something", "value2" : "somethingelse", "value3" : "anything" }
},
```
The values in the body are passed to IFTTT, but you only need to include them if you actually have values to pass.  For instance, I pass the temperatures that I want IFTTT to send to my Nest.  I also have the button turn off my Wemo lights, which don't need values, and it just ignores them.  If you use the same event name for multiple applets, IFTTT will trigger all of them with one push of the button.

I have to set the protocol to udp since I have newer dash buttons -- if this doesn't work for you, check the readme and edit the protocol setting accordingly.

**Comment by fun4stuff** [comment]
Thanks elmedico! Sorry I'm late!
